services:

  api:
    build:
      context: .
      dockerfile: src/PartageTexte.Api/Dockerfile
    container_name: partage-texte-api
    ports:
      - "5037:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Chiffrement__Cle: "RVybXs9k6SQw+n6ix3icQ1BkhbPU6mSm6dUkEJpg1Uc="
      Stockage__Chemin: /data/partages
    volumes:
      - partages_data:/data/partages
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: src/PartageTexte.Web/Dockerfile
    container_name: partage-texte-web
    ports:
      - "5110:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Api__UrlBase: "http://api:8080"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  partages_data:
